import scons.sconsbuild
br = scons.sconsbuild.BuildRules('ts');

br.CppLibrary(
    name = 'file_utils',
    srcs = ['file_utils.cpp'],
    hdrs = [ 'file_utils.hpp']);

br.CppLibrary(
    name = 'hash',
    hdrs = [ 'hash.hpp'],
    deps = []);

br.CppLibrary(
    name = 'tuple',
    hdrs = [ 'tuple.hpp'],
    deps = []);

br.CppLibrary(
    name = 'type_traits',
    hdrs = [ 'type_traits.hpp'],
    deps = []);

br.CppLibrary(
    name = 'stl_utils',
    hdrs = [ 'stl_utils.hpp'],
    deps = []);

br.CppLibrary(
    name = 'unordered_map',
    hdrs = [ 'unordered_map.hpp'],
    deps = []);

br.CppLibrary(
    name = 'hashed_sequential_counter',
    hdrs = ['hashed_sequential_counter.hpp'],
    deps = []);

br.CppTest(
    name = 'hash_test',
    srcs = [ 'hash_test.cpp'],
    deps = [':hash',
            'testing/gtest:gtest_thoughtspot_main']);

br.CppTest(
    name = 'unordered_map_test',
    srcs = [ 'unordered_map_test.cpp'],
    deps = [':unordered_map',
            'testing/gtest:gtest_thoughtspot_main']);
